# Backend
backend = "glx";
glx-copy-from-front = false;

# Blur
blur-method = "dual_kawase";
blur-strength = 8;
blur-background = true;
blur-background-frame = true;

# Apply blur only to kitty
blur-background-exclude = [
    "class_g != 'kitty'"
];

# Opacity
inactive-opacity = 1.0;
active-opacity = 1.0;

# Kitty background opacity
opacity-rule = [
    "85:class_g = 'kitty'"
];

# Shadows
shadow = false;

# Fading
fading = false;
